package com.vxplore.core.common

enum class EmitType {
    BaseUrl,
    AppVersion,
    States,
    Districts,
    Pincodes,
    Otp,
    VENDORS,
    PAPER_CODE,
    TOTAL_SOLD_PAPER,
    COUPONS,
    SEARCH_VENDORS,
    BackendError,
    Navigate,
    Loading,
    MOVIEWS,
    ERROR,
    IntroStatus,
    NetworkError,
    INFORM,
    PAPERS,
    DUE,
    PAPERS_LIST_SIZE,
    PaperSold,
    PaperReturn,
    TodayEachPaperSold,
    IS_ADDED,
    PDF_URL,
    PHONE,
    DISTRIBUTOR_NAME,
    DISTRIBUTOR_ID,


}